.TH knxm_release 1 

.SH NAME
unzipconv \- unzip and conv

.SH SYNOPSIS
.\" usage
.B unzipconv.py 
.I zipfile
[
..
]
[
-d
.I outputdir 
]
[
--decode
.I codec
]
[
--language
.I Language
]

.SH DESCRIPTION
.I unzipconv
is a small program like unzip command.
The encode of the files in the zip file may be detected automatically.

.SH AUTHORS
NUMATA, Yacehide (nu+y at math sci hokudai ac jp)
